INSERT INTO genres(genre_name)
VALUES ('Джаз'), 
       ('Блюз'), 
       ('Шансон'),
       ('Рок'),
       ('Поп-музыка'),
       ('Хип-хоп'),
       ('Классическая музыка');

INSERT INTO performers(performers_name)
VALUES ('Макс Роуч'), 
       ('Фрэнк Синатра'), 
       ('Роберт Лерой Джонсон'),
       ('Эрик Клэптон'),
       ('Михаил Круг'),
       ('Сергей Трофимов'),
       ('The Beatles'),
       ('Queen'),
       ('Полина Гагарина'),
       ('Дима Билан'),
       ('Баста'),
       ('Эминем'),
       ('Людвиг ван Бетховен');

INSERT INTO genres_performers(genres_id, performers_id) 
VALUES(1, 1),
      (1, 2),
      (2, 3),
      (2, 4),
      (3, 5),
      (3, 6),
      (4, 7),
      (4, 8),
      (5, 9),
      (5, 10),
      (5, 11),
      (6, 11),
      (6, 12),
      (7, 13);

INSERT INTO albums(album_title, year_issue) 
VALUES('We Insist!', 1960),
      ('Christmas Songs by Sinatra', 1948),
      ('Feel Like Going Home - A Film By Martin Scorsese', 2003),
      ('Unplugged', 1992),
      ('Исповедь', 2003),
      ('Война и мир', 2000),
      ('The Beatles', 1948),
      ('Queen II', 1974),
      ('Попроси у облаков', 2007),
      ('Я ночной хулиган', 2003),
      ('Баста 5, Часть 2', 2018),
      ('The Eminem Show', 2020),
      ('Леонора & Симфония №7', 1988);

INSERT INTO performers_albums(albums_id, performers_id) 
VALUES(1, 1),
      (2, 2),
      (3, 3),
      (4, 4),
      (5, 5),
      (6, 6),
      (7, 7),
      (8, 8),
      (9, 9),
      (10, 10),
      (11, 11),
      (12, 12),
      (13, 13);

INSERT INTO tracks(track_name, track_duration, album_id) 
VALUES('Freedom day', '6:09', 1),
      ('Driva man', '5:18', 1),
      ('White christmas', '3:24', 2),
      ('Silent Night, Holy Night', '3:17', 2),
      ('Traveling Riverside Blues', '2:45', 3),
      ('Hellhound on My Trail', '2:35', 3),
      ('Signe', '3:13', 4),
      ('Before You Accuse Me', '3:36', 4),
      ('Исповедь', '5:18', 5),
      ('Владимирский Централ 2 (Еврейский Арестант)', '4:27', 5),
      ('Эх, дал бы кто в займы', '3:48', 6),
      ('Ветерок', '3:38', 6),
      ('Birthday', '2:43', 7),
      ('Julia', '2:54', 7),
      ('ProcessionMy', '1:13', 8),
      ('The Loser in the End', '4:04', 8),
      ('Я твоя', '2:50', 9),
      ('Я тебя не прощу никогда', '4:12', 9),
      ('Я ночной хулиган', '3:13', 10),
      ('Звёздочка Моя Ясная', '3:43', 10),
      ('Выпускной (Медлячок)', '5:35', 11),
      ('Черт', '4:40', 11),
      ('Soldier', '3:47', 12),
      ('Business', '4:12', 12),
      ('Леонора in C Major, Op. 72b: III. Увертюра', '12:32', 13);

INSERT INTO compilations(compilation_name, year_issue) 
VALUES('Quiet As Its Kept', 1964),
      ('Baby Blue Eyes', 2017),
      ('King Of The Delta Blues', 2020),
      ('Complete Clapton', 2007),
      ('50 лучших песен (Большая коллекция шансона)', 2013),
      ('Пересмешник', 2020),
      ('Tomorrow Never Knows', 2012),
      ('Queen Forever (Deluxe Edition)', 2014),
      ('Попроси у облаков (2018 Version)', 2018),
      ('На берегу неба', 2004),
      ('Баста+', 2013),
      ('Curtain Call 2', 2022);

INSERT INTO tracks_compilation (track_id, compilation_id) 
VALUES(1, 1),
      (2, 1),
      (3, 2),
      (4, 2),
      (5, 3),
      (6, 3),
      (7, 4),
      (8, 4),
      (9, 5),
      (10, 5),
      (11, 6),
      (12, 6),
      (13, 7),
      (14, 7),
      (15, 8),
      (16, 8),
      (17, 9),
      (18, 9),
      (19, 10),
      (20, 10),
      (21, 11),
      (22, 11),
      (23, 12),
      (24, 12);